[build]
command = """
    scripts/build-glean-metadata.py
    npm run build
    fi
"""
environment = { PYTHON_VERSION = "3.7" }
publish = "public"

[context.production]
  [context.production.environment]
  CONTEXT = "production"